version: "3"
services:
  web:
    build: .
    ports:
      - "5101:5101"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"